"""fix profile column name

Revision ID: 1ff1d18eb257
Revises: 71a301a532a5
Create Date: 2025-03-13 23:22:39.711662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1ff1d18eb257'
down_revision: Union[str, None] = '71a301a532a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_pic_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('user', 'proifle_pic_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('proifle_pic_url', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('user', 'profile_pic_url')
    # ### end Alembic commands ###
